version: 2.1

jobs:
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: >
            echo "The command above installs Heroku, the command below deploys.
            What you do inbetween is up to you!"
      - heroku/deploy-via-git

orbs:
  maven: circleci/maven@0.0.12
  heroku: circleci/heroku@1.2.6

deployment:
  staging:
    branch: master
    heroku:
      appname: labcvds

workflows:
  maven_test:
    jobs:
      - maven/test # checkout, build, test, and upload test results
